spring:
  application:
    name: api-gateway-routefilter

server:
  port: 1132

zuul:
  routes:
    service:
      path: /service/**
      serviceId: eureka-client-for-gateway-routecfg

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/